---
- name: AWS Environment Creation
  hosts: localhost
  gather_facts: False
  vars_prompt:
    - name: appuser
      prompt: "What is the shell username you want"
      private: no
      when: appuser is not defined

    - name: appuser_pw
      prompt: "What is the shell user password? REQUIRED for EC2"
      private: yes
      when: appuser_pw is not defined


  roles:
    - provision-vpc
    - provision-s3
    - role: provision-ec2
      when:
        - appuser != ''
        - appuser_pw != ''
