---
- name: Package installation and service checks
  hosts: all
  become: True
  gather_facts: True

  tasks:
    - name: Install Greengrass
      include_role:
        name: on-prem-rpi-install-greengrass
