---
- name: Install ssm, requires input
  hosts: all
  remote_user: "{{ remote_user | default('pi') }}"
  gather_facts: True
  become: True
  become_method: sudo
  vars_prompt:
    - name: ssm_id
      prompt: "What is the Hybrid SSM ID?"
      private: no
      when: ssm_id is not defined

    - name: code_id
      prompt: "What is the Hybrid SSM code?"
      private: no
      when: code_id is not defined

    - name: ssm_region
      prompt: "What is the region we will be managing the machine from?"
      private: no
      when: ssm_region is not defined

roles:
  - onprem-install-ssm
