---
- name: Package installation and service checks
  hosts: all
  remote_user: pi
  become: True
  gather_facts: True

  pre_tasks:
    - name: Download roles if we are doing local dev work
      shell: ansible-galaxy install -r roles/requirements.yml -p ./roles/ --force
      delegate_to: localhost
      when: lookup('env','USER') != 'awx'
      run_once: true
      connection: local
      become: False      

  # tasks:
  #   - name: Install Greengrass
  #     include_role:
  #       name: on-prem-rpi-install-greengrass
