---
- name: Install opensprinkler
  hosts: all
  # Usually installed on a Rpi, defaults to user 'pi'
  remote_user: "{{ remote_user | default('pi') }}"
  become: True
  gather_facts: False

  pre_tasks:
    - name: Download roles if we are doing local dev work
      shell: ansible-galaxy install -p ../roles/ rileyschuit.rpi-opensprinkler
      delegate_to: localhost
      when: lookup('env','USER') != 'awx'
      run_once: true
      connection: local
      become: False

  tasks:
    - name: Check that OpenSprinkler is not running and install
      block:
        - name: Requied pip module
          pip:
            name: psutil
            state: present

        - name: Check for process running
          pids:
            name: OpenSprinkler
          register: opensprinkler_pid

      rescue:
        - name: Include Installation role
          include_role:
            name: rileyschuit.rpi-opensprinkler

    - name: Set Hostname
      hostname:
        name: "{{ hostname | default('opensprinkler')}}"
